alias python=python2


alias ls='ls --color=auto --group-directories-first'
alias la='ls -A'
alias ll='ls -lah --group-directories-first'
alias l.='ls -d .* --color=auto'

alias apt-get='apt-get -y'

alias clip='xclip -selection c'

